name: Release
on:
  push:
    tags:
    - "v*"
permissions:
  contents: write
env:
  GH_ANNOTATION: true
jobs:
  archive:
    runs-on: ubuntu-20.04
    name: Build SMI Extension
    timeout-minutes: 30
    env:
      ARCHIVES: /home/runner/archives
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
      with:
        go-version: '1.16.6'
    - name: Build SMI Helm Package
      run: |
        mkdir -p $ARCHIVES
        bin/helm-build package
        cp -r ./target/helm $ARCHIVES
    - name: Upload artifact
      uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074
      with:
        name: build-archives
        path: /home/runner/archives
  chart_deploy:
    name: Helm chart deploy
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    needs: [archive]
    steps:
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      with:
        ref: gh-pages
        fetch-depth: 0
    - name: Download CLI archives
      uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60
      with:
        name: build-archives
        path: build-archives
    - name: Install Helm
      uses: azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab
    - name: Helm chart creation and upload
      run: |
        helm repo index --merge index.yaml build-archives/helm
        mv build-archives/helm/index.yaml ./index.yaml
        cp -r build-archives/helm/. ./
        # update version in install script
        sed -i 's/LINKERD_SMI_VERSION:-.*/LINKERD_SMI_VERSION:-"${{needs.gh_release.outputs.tag}}"}/' ./install
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add linkerd-smi-*.tgz index.yaml install
        git commit -sm "Add new Helm Chart ${{ needs.gh_release.outputs.tag }}"
        git push
